prefix = "p/"

[events]
events_path = "src/events"
commands_path = "src/commands"
log_deleted_messages = true

[commands]
vile_imagery_path = "resources/vileimagery"
pepper_path = "resources/the_peppers"